"""empty message

Revision ID: 9040c25a4248
Revises: 
Create Date: 2018-06-15 22:28:16.954763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9040c25a4248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('header', sa.String(length=255), nullable=True),
    sa.Column('words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_header'), 'vacancy', ['header'], unique=False)
    op.create_index(op.f('ix_vacancy_vacancy_id'), 'vacancy', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_vacancy_id'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_header'), table_name='vacancy')
    op.drop_table('vacancy')
    # ### end Alembic commands ###
