"""empty message

Revision ID: e59b1be997eb
Revises: e9c5cc215f95
Create Date: 2018-06-17 00:01:53.396956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59b1be997eb'
down_revision = 'e9c5cc215f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('vector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'vector')
    # ### end Alembic commands ###
